classdef feaimport
    %FEAIMPORT Summary of this class goes here
    %   Detailed explanation goes here

	properties
		xdot	(1,1)	double	{mustBeNonnegative}				= 0;		% Diaphragm velocity in [m/s]
		sd		(1,1)	double	{mustBeNonnegative}				= 0;		% Diaphragm area in [m2]
		fnamediaphragmf	(1,1)	string							= "";		% Filename including location for pressure results diaphragm front
		fnamediaphragmr	(1,1)	string							= "";		% Filename including location for pressure results diaphragm rear
		fnamexdottopres (1,1)	string							= "";		% Filename including location for pressure at microphone location
		fnamemicff		(1,1)	string							= "";		% Filename including location for pressure result beyond the mesh domain
	end

	properties (Dependent)
		fans																% Frequencies in ANSYS result files.
		zafront																% Acoustic impedance front side of diaphragm
		zarear																% Acoustic impedance rear side of diaphragm
		xdot2pres															% Pressure at specific location at 1m/s diaphragm velocity
		xdot2presff															% Pressure at specific location at 1m/s diaphragm velocity (Far-field)
	end

    methods
        function obj = feaimport
            %FEAIMPORT Construct an instance of this class
            %   Detailed explanation goes here
		end
		function val = get.zafront(obj)
			%ZAFRONT

			% Import pressure results:
			imp		= fea.feaimport.importansyspres(obj.fnamediaphragmf);

			% Obtain complex pressure:
			p		= imp.RealPa + 1i * imp.ImaginaryPa;

			% Volume velocity:
			Q		= obj.xdot * obj.sd;

			% Acoustic impedance:
			val		= (p / Q).';
		end
		function val = get.zarear(obj)
			%ZAREAR

			% Import pressure results:
			imp		= fea.feaimport.importansyspres(obj.fnamediaphragmr);

			% Obtain complex pressure:
			p		= imp.RealPa + 1i * imp.ImaginaryPa;

			% Volume velocity:
			Q		= -obj.xdot * obj.sd;

			% Acoustic impedance:
			val		= (p / Q).';
		end
		function val = get.fans(obj)
			%FANS ANSYS frequency

			% Import pressure results front and rear side of diaphragm:
			if obj.fnamediaphragmf ~= ""
				impf	= fea.feaimport.importansyspres( ...
					obj.fnamediaphragmf);
				ff		= impf.FrequencyHz;
				val		= ff.';
			end
			
			if obj.fnamediaphragmr ~= ""
				impr	= fea.feaimport.importansyspres( ...
					obj.fnamediaphragmr);
				fr		= impr.FrequencyHz;
				val		= fr.';
			end

		end
		function val = get.xdot2pres(obj)
			%XDOT2PRES

			% Import pressure results:
			imp		= fea.feaimport.importansyspres(obj.fnamexdottopres);

			% Obtain complex pressure:
			p		= imp.RealPa + 1i * imp.ImaginaryPa;

			% Pressure at 1m/s diaphragm velocity:
			val		= (p / obj.xdot).';
		end
		function val = get.xdot2presff(obj)
			%XDOT2PRESFF Diaphragm velocity to pressure in the far field.

			% Import pressure results:
			imp		= fea.feaimport.importansyspresff(obj.fnamemicff).FarfieldMaxPresPa;

			% Pressure at 1m/s diaphragm velocity:
			val		= (imp ./ obj.xdot).';
		end
	end

	methods (Static)
		function val = importansyspres(filename, dataLines)
			%IMPORTFILE Import data from a text file
			%  PDIAFRONT21INCHSUB = IMPORTFILE(FILENAME) reads data from text file
			%  FILENAME for the default selection.  Returns the data as a table.
			%
			%  PDIAFRONT21INCHSUB = IMPORTFILE(FILE, DATALINES) reads data for the
			%  specified row interval(s) of text file FILENAME. Specify DATALINES as
			%  a positive scalar integer or a N-by-2 array of positive scalar
			%  integers for dis-contiguous row intervals.
			%
			%  Example:
			%  pdiafront21inchsub = importfile("D:\OneDrive - Spierings Mobile Cranes\Werkmap - Spierings\11. MATLAB\tbxs\audiotbx\toolbox\examples\ansysexport\pdiafront21inchsub.txt", [2, Inf]);
			%
			%  See also READTABLE.
			%
			% Auto-generated by MATLAB on 14-May-2024 21:49:19
			
			%% Input handling
			
			% If dataLines is not specified, define defaults
			if nargin < 2
				dataLines = [2, Inf];
			end
			
			%% Set up the Import Options and import the data
			opts = delimitedTextImportOptions("NumVariables", 5);
			
			% Specify range and delimiter
			opts.DataLines = dataLines;
			opts.Delimiter = "\t";
			
			% Specify column names and types
			opts.VariableNames = ["FrequencyHz", "AmplitudeMPa", "PhaseAngledeg", "RealMPa", "ImaginaryMPa"];
			opts.VariableTypes = ["double", "double", "double", "double", "double"];
			
			% Specify file level properties
			opts.ExtraColumnsRule = "ignore";
			opts.EmptyLineRule = "read";
			
			% Import the data
			val = readtable(filename, opts);

			% Convert MPa to Pa;
			val.AmplitudeMPa(:)		= val.AmplitudeMPa(:) * 1e6;
			val.RealMPa(:)			= val.RealMPa(:) * 1e6;
			val.ImaginaryMPa(:)		= val.ImaginaryMPa(:) * 1e6;

			% Rename Variables:
			val.Properties.VariableNames(2)		= "AmplitudePa";
			val.Properties.VariableNames(4)		= "RealPa";
			val.Properties.VariableNames(5)		= "ImaginaryPa";
		end
		function val = importansyspresff(filename, dataLines)
			%IMPORTFILE Import data from a text file
			%  V1CPRESMICFF = IMPORTFILE(FILENAME) reads data from text file
			%  FILENAME for the default selection.  Returns the data as a table.
			%
			%  V1CPRESMICFF = IMPORTFILE(FILE, DATALINES) reads data for the
			%  specified row interval(s) of text file FILENAME. Specify DATALINES as
			%  a positive scalar integer or a N-by-2 array of positive scalar
			%  integers for dis-contiguous row intervals.
			%
			%  Example:
			%  v1cpresmicff = importfile("D:\OneDrive - Spierings Mobile Cranes\Werkmap - Prive\_Audio\2024-06-05 BC subwoofer\ansys\bcsubwoofer\v1cpresmicff.txt", [2, Inf]);
			%
			%  See also READTABLE.
			%
			% Auto-generated by MATLAB on 03-Jul-2024 16:46:03
			
			%% Input handling
			
			% If dataLines is not specified, define defaults
			if nargin < 2
				dataLines = [2, Inf];
			end
			
			%% Set up the Import Options and import the data
			opts = delimitedTextImportOptions("NumVariables", 2);
			
			% Specify range and delimiter
			opts.DataLines = dataLines;
			opts.Delimiter = "\t";
			
			% Specify column names and types
			opts.VariableNames = ["Frequency", "FarfieldMaximumPressureMicMPa"];
			opts.VariableTypes = ["double", "double"];
			
			% Specify file level properties
			opts.ExtraColumnsRule = "ignore";
			opts.EmptyLineRule = "read";
			
			% Import the data
			val = readtable(filename, opts);

			% Convert [MPa] to [Pa]:
			val.Properties.VariableNames(2)		= "FarfieldMaxPresPa";
			val.FarfieldMaxPresPa				= val.FarfieldMaxPresPa * 1e6;

			
		end
	end
end

